spring.application.name=spring-ai-chatbot

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=qwen3:1.7b

app.ai.system-prompt=You are a helpful Java teacher. Explain concepts simply.